services:

  mysql:
    image: mysql:8.4
    container_name: fcv-citas-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Bogota

    ports:
      - "${MYSQL_PORT:-3307}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s


  citas-api-dev:
    image: maven:3.9-eclipse-temurin-21
    container_name: fcv-citas-api-dev
    restart: unless-stopped

    working_dir: /workspace

    volumes:
      - ./citas-api:/workspace
      - maven_cache:/root/.m2

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

    ports:
      - "${API_PORT:-8080}:8080"

    depends_on:
      mysql:
        condition: service_healthy

    command:
      - bash
      - -lc
      - tail -f /dev/null


  citas-web-dev:
    image: node:24-alpine
    container_name: fcv-citas-web-dev
    restart: unless-stopped

    working_dir: /workspace

    volumes:
      - ./citas-web:/workspace
      - node_cache:/root/.npm

    ports:
      - "${REACT_PORT:-5173}:5173"
      - "${ANGULAR_PORT:-4200}:4200"

    depends_on:
      - citas-api-dev

    command:
      - sh
      - -lc
      - tail -f /dev/null


volumes:
  mysql_data:
  maven_cache:
  node_cache: